#
# Module manifest for module 'POSHOrigin_vSphere'
#
# Generated by: Brandon Olin
#
# Generated on: 9/30/2015
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'POSHOrigin_vSphere.psm1'

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = 'af4099cf-30a1-44eb-8c74-a10948245227'

# Author of this module
Author = 'Brandon Olin'

# Company or vendor of this module
CompanyName = 'Columbia Sportswear'

# Copyright statement for this module
Copyright = '(c) 2015 Columbia Sportswear. All rights reserved.'

# Description of the functionality provided by this module
Description = 'POSHOrigin DSC module to manage VMware vSphere NetScaler resources.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.0'

# DSC resources to export from this module
DscResourcesToExport = 'vSphere_VM'
}